services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: jobnest
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - jobnest_pg:/var/lib/postgresql/data

volumes:
  jobnest_pg:
